name: Cypress Tests

on:
  push:
    branches:
      - Empty
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install
        working-directory: Projects/Cypress/

      # - name: Install Cypress Binary
      #   run: npx cypress install

      - name: Run Cypress Test
        run: npx cypress run --browser chrome
        working-directory: Projects/Cypress/