name: Cypress Tests

on:
  push:
    branches:
      - Empty
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Log File Structure
        run: ls -R Projects/Cypress

      - name: Install Dependencies
        run: npm install
        working-directory: Projects/Cypress

      - name: Verify Support File Exists
        run: |
          if [ ! -f Projects/Cypress/support/e2e.js ]; then
            echo "Support file not found!"
            exit 1
          fi

      - name: Run Cypress Test
        run: npx cypress run --browser chrome
        working-directory: Projects/Cypress